# Generated by Django 5.0.6 on 2024-07-29 18:58

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='price_amount',
            new_name='start_bid_amount',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='price_currency_code',
            new_name='start_bid_currency_code',
        ),
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='bid',
            name='edited_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='edited_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='end_bid_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Rejected'), (2, 'Accepted'), (3, 'Cancelled'), (4, 'Cancel Requested')], default=0),
        ),
    ]
