# Generated by Django 5.1.7 on 2025-03-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_price_amount_task_start_bid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_bid_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
