# Generated by Django 5.1.7 on 2025-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bid_cancelled_alter_task_end_bid_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_bid_currency_code',
        ),
        migrations.AddField(
            model_name='bid',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
