# Generated by Django 5.1.7 on 2025-11-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_walletnonce_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContractProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42, unique=True)),
                ('latest_block', models.IntegerField(default=0)),
            ],
        ),
    ]
