# Generated by Django 5.1.7 on 2025-11-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_smartcontractprocessor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bid',
            name='unique_together',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='end_date',
            new_name='complete_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='finalized',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='edited_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='edited_date',
        ),
        migrations.AddField(
            model_name='bid',
            name='uid',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='wallet_address',
            field=models.CharField(default=0, max_length=42, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='uid',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='wallet_address',
            field=models.CharField(default=0, max_length=42, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_bid_amount',
            field=models.IntegerField(),
        ),
    ]
