# Generated by Django 5.1.7 on 2025-11-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_bid_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cancelled',
        ),
    ]
