# Generated by Django 5.1.7 on 2025-11-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_task_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='wallet_address',
            field=models.CharField(max_length=42),
        ),
    ]
