# Generated by Django 5.1.7 on 2025-11-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_task_wallet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='amount',
        ),
        migrations.AlterField(
            model_name='bid',
            name='wallet_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userwallet'),
        ),
    ]
