# Generated by Django 5.1.7 on 2025-11-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_bid_amount_alter_bid_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
