# Generated by Django 5.1.7 on 2025-11-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='wallet_address',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
