# Generated by Django 5.1.7 on 2025-11-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_bid_amount_alter_bid_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='wallet_address',
            field=models.CharField(max_length=42),
        ),
    ]
