# Generated by Django 5.1.7 on 2025-11-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_bid_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='uid',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('uid', 'task')},
        ),
    ]
